version: 2
jobs:
  build:
    docker:
      - image: node:current

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install node_modules
          command: npm i
      - run:
          name: deploy
          command: npm run deploy
    branches:
      only:
        - dev
