jobs:
  build:
    docker:
      - image: node:current
    steps:
      - run:
          name: install hexo
          command: npm i -g hexo
      - run:
          name: check path
          command: pwd && ls
      - run:
          name: deploy
          command: hexo g -d
    branches:
      only:
        - dev
