version: 2
jobs:
  build:
    docker:
      - image: node:current

    working_directory: ~/repo

    steps:
      - run:
          name: install hexo
          command: npm i -g hexo
      - run:
          name: deploy
          command: hexo g -d
    branches:
      only:
        - dev
