# Search
search:
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
  - slug: github
    url: https://github.com/stkevintan
  - slug: twitter
    url: https://twitter.com/kevinsfork
  - slug: rss
url: /atom.xml

gitalk:
  on: true
  owner: le0l1
  repo: le0l1.github.io
  admin: ["le0l1"]
  clientID: af4940ed9c1ad03fd197
  clientSecret: ccca06c8b1052d30c8d545445f47895b1d2468e6
